// Node.js script to update src/siteVersion.ts from the latest version in changelog.md
const fs = require('fs');
const path = require('path');

const changelogPath = path.join(__dirname, '..', 'changelog.md');
const versionFilePath = path.join(__dirname, '..', 'src', 'siteVersion.ts');

const changelog = fs.readFileSync(changelogPath, 'utf8');
const versionMatch = changelog.match(/^## (v[0-9]+\.[0-9]+\.[0-9]+)/m);

if (!versionMatch) {
  console.error('Could not find version in changelog.md');
  process.exit(1);
}

const version = versionMatch[1];
const versionFileContent = `// Site version is managed here for easy import and update.\n// This file is auto-generated by scripts/updateSiteVersion.js\nexport const SITE_VERSION = \"${version}\";\n`;

fs.writeFileSync(versionFilePath, versionFileContent, 'utf8');
console.log(`Updated site version to ${version}`);
